// Top-level build file where you can add configuration options common to all sub-projects/modules.
apply from: 'buildsystem/dependencies.gradle'

buildscript {
//    ext.lambdaVersion = '3.7.0'
    repositories {

        maven { url "https://maven.aliyun.com/repository/google"}
        maven { url "https://maven.aliyun.com/repository/central"}
        maven { url "https://maven.aliyun.com/repository/jcenter"}
        maven { url "https://maven.aliyun.com/repository/gradle-plugin"}
        maven { url 'http://developer.huawei.com/repo/'}
        maven { url "https://bintray.com/wechat-sdk-team/maven"}
        maven { url "https://maven.aliyun.com/nexus/content/groups/public/"}

        jcenter()
        mavenCentral()
        google()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:4.0.1'
//        classpath "me.tatarka:gradle-retrolambda:$lambdaVersion"
    }
}

allprojects {
    repositories {

        maven { url "https://maven.aliyun.com/repository/google"}
        maven { url "https://maven.aliyun.com/repository/central"}
        maven { url "https://maven.aliyun.com/repository/jcenter"}
        maven { url "https://maven.aliyun.com/repository/gradle-plugin"}
        maven { url 'http://developer.huawei.com/repo/'}
        maven { url "https://bintray.com/wechat-sdk-team/maven"}
        maven { url "https://maven.aliyun.com/nexus/content/groups/public/"}

        jcenter()
        maven { url "https://jitpack.io" }
        google()
    }
}

allprojects {
    ext {
        androidApplicationId = 'com.freedom.lauzy.ticktockmusic'
        androidVersionCode = 1
        androidVersionName = "1.0"
        testInstrumentationRunner = "android.support.test.runner.AndroidJUnitRunner"
        testApplicationId = 'com.freedom.lauzy.ticktockmusic.test'
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
